### ISSUE TITLE
Fixing Comunication

### ISSUE THREAD

**Issue by StefanRandelzhofer** [SBester001/Controller#1]
E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: diy.esp8266.controller, PID: 8555
    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintWriter.write(java.lang.String)' on a null object reference
        at diy.esp8266.controller.Calculator.run(Calculator.java:47)

**Comment by SBester001** [comment]
Ok, bug was fixed
